package com.lnkj.android.mapchooseaddress

import com.chad.library.adapter.base.BaseQuickAdapter
import com.chad.library.adapter.base.viewholder.BaseViewHolder

class ItemAdapter(data: MutableList<Any>): BaseQuickAdapter<Any, BaseViewHolder>(R.layout.item, data) {

    init {
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
        addData(Any())
    }

    override fun convert(holder: BaseViewHolder, item: Any) {

    }
}